# Generated by Django 4.2.23 on 2025-08-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilorganizacao',
            name='facebook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='perfilorganizacao',
            name='instagram',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
