# Generated by Django 4.2.23 on 2025-08-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_perfilorganizacao_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilvoluntario',
            name='organizacoes',
        ),
        migrations.RemoveField(
            model_name='perfilvoluntario',
            name='user',
        ),
        migrations.DeleteModel(
            name='PerfilOrganizacao',
        ),
        migrations.DeleteModel(
            name='PerfilVoluntario',
        ),
    ]
