# Generated by Django 4.2.23 on 2025-08-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_perfilvoluntario_organizacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(default='', max_length=11, verbose_name='Telefone'),
        ),
    ]
