# Generated by Django 4.2.23 on 2025-07-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome da Organização', max_length=45, unique=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('email', models.CharField(max_length=320, unique=True)),
                ('senha', models.CharField(max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
