# Generated by Django 4.2.23 on 2025-07-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_porte_raca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='organizacao',
            name='voluntario',
            field=models.ManyToManyField(related_name='organizações', to='sistema.voluntario'),
        ),
    ]
