# Generated by Django 4.2.23 on 2025-07-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_voluntario_organizacao_voluntario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('senha', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=11, unique=True)),
                ('email', models.CharField(max_length=320, unique=True)),
                ('nome_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
