# Generated by Django 4.2.23 on 2025-07-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perdidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
                ('data_nascimento', models.DateField(default='2000-01-01')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets_perdidos', to='sistema.organizacao')),
                ('porte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets_perdidos', to='sistema.porte')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets_perdidos', to='sistema.raca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets_perdidos', to='sistema.usuario')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets_perdidos', to='sistema.voluntario')),
            ],
        ),
    ]
