# Generated by Django 4.2.23 on 2025-07-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_perdidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdidos',
            name='castrado',
            field=models.CharField(choices=[('s', 'sim'), ('n', 'nao')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='perdidos',
            name='sexo',
            field=models.CharField(choices=[('m', 'macho'), ('f', 'femea')], default='m', max_length=1),
        ),
        migrations.AddField(
            model_name='perdidos',
            name='vacinado',
            field=models.CharField(choices=[('s', 'sim'), ('n', 'nao')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='castrado',
            field=models.CharField(choices=[('s', 'sim'), ('n', 'nao')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('m', 'macho'), ('f', 'femea')], default='m', max_length=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='vacinado',
            field=models.CharField(choices=[('s', 'sim'), ('n', 'nao')], default='n', max_length=1),
        ),
    ]
