# Generated by Django 4.2.23 on 2025-07-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_perdidos_castrado_perdidos_sexo_perdidos_vacinado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacao',
            options={'verbose_name': 'Organização', 'verbose_name_plural': 'Organizações'},
        ),
    ]
