# Generated by Django 4.2.23 on 2025-07-09 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('sistema', '0008_perdidos_castrado_perdidos_sexo_perdidos_vacinado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacao',
            options={'verbose_name': 'Organização', 'verbose_name_plural': 'Organizações'},
        ),
        migrations.AddField(
            model_name='perdidos',
            name='foto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
