# Generated by Django 4.2.23 on 2025-07-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_alter_organizacao_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacao',
            name='voluntario',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='voluntario',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Voluntario',
        ),
    ]
