# Generated by Django 4.2.23 on 2025-08-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_alter_organizacao_options_perdidos_foto_pet_foto'),
        ('sistema', '0010_remove_organizacao_voluntario_and_more'),
    ]

    operations = [
    ]
