# Generated by Django 4.2.23 on 2025-08-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_merge_20250814_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdidos',
            name='porte',
            field=models.CharField(choices=[('p', 'Pequeno'), ('m', 'Médio'), ('g', 'Grande')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='porte',
            field=models.CharField(choices=[('p', 'Pequeno'), ('m', 'Médio'), ('g', 'Grande')], default='p', max_length=1),
        ),
        migrations.DeleteModel(
            name='Porte',
        ),
    ]
