# Generated by Django 4.2.23 on 2025-09-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_alter_perdidos_porte_alter_pet_porte_delete_porte'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdidos',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pet',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='perdidos',
            name='tipo',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('outro', 'Outro')], max_length=25),
        ),
        migrations.AlterField(
            model_name='pet',
            name='tipo',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('outro', 'Outro')], max_length=25),
        ),
    ]
