# Generated by Django 4.2.23 on 2025-08-28 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0012_alter_perdidos_porte_alter_pet_porte_delete_porte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perdidos',
            name='org',
        ),
        migrations.AddField(
            model_name='organizacao',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perdidos',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('admin', 'Administrador'), ('colab', 'Colaborador')], max_length=5)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema.organizacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
