# Generated by Django 4.2.23 on 2025-09-10 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0013_perdidos_nome_pet_nome_alter_perdidos_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='faceboook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
