# Generated by Django 4.2.23 on 2025-09-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_perdidos_nome_pet_nome_alter_perdidos_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perdidos',
            name='org',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='org',
        ),
        migrations.DeleteModel(
            name='Organizacao',
        ),
    ]
