# Generated by Django 4.2.23 on 2025-09-12 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0014_organizacao_admin_organizacao_faceboook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perdidos',
            old_name='sexo',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='sexo',
            new_name='genero',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='org',
        ),
        migrations.AddField(
            model_name='perdidos',
            name='dono',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='perdidos_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perdidos',
            name='local',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pet',
            name='local',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='perdidos',
            name='foto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets_organizacao', to='sistema.organizacao'),
        ),
    ]
