# Generated by Django 4.2.23 on 2025-09-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_rename_sexo_perdidos_genero_rename_sexo_pet_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='local',
        ),
    ]
