# Generated by Django 4.2.23 on 2025-09-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('sistema', '0016_remove_pet_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='foto_perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizacoes', to='uploader.image', verbose_name='Foto de Perfil'),
        ),
    ]
