# Generated by Django 4.2.23 on 2025-09-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0017_organizacao_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdidos',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
