# Generated by Django 4.2.23 on 2025-09-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0019_pet_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdidos',
            name='castrado',
            field=models.CharField(choices=[('sim', 'sim'), ('nao', 'nao')], default='n', max_length=3),
        ),
        migrations.AlterField(
            model_name='perdidos',
            name='genero',
            field=models.CharField(choices=[('macho', 'macho'), ('femea', 'femea')], default='m', max_length=5),
        ),
        migrations.AlterField(
            model_name='perdidos',
            name='porte',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], default='p', max_length=7),
        ),
        migrations.AlterField(
            model_name='perdidos',
            name='tipo',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('passaro', 'Pássaro'), ('outro', 'Outro')], max_length=25),
        ),
        migrations.AlterField(
            model_name='perdidos',
            name='vacinado',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao'), ('parcialmente', 'Parcialmente'), ('nao-sei', 'Não sei')], default='n', max_length=12),
        ),
        migrations.AlterField(
            model_name='pet',
            name='castrado',
            field=models.CharField(choices=[('sim', 'sim'), ('nao', 'nao')], default='n', max_length=3),
        ),
        migrations.AlterField(
            model_name='pet',
            name='genero',
            field=models.CharField(choices=[('macho', 'macho'), ('femea', 'femea')], default='m', max_length=5),
        ),
        migrations.AlterField(
            model_name='pet',
            name='porte',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], default='p', max_length=7),
        ),
        migrations.AlterField(
            model_name='pet',
            name='tipo',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('passaro', 'Pássaro'), ('outro', 'Outro')], max_length=25),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vacinado',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao'), ('parcialmente', 'Parcialmente'), ('nao-sei', 'Não sei')], default='n', max_length=12),
        ),
    ]
