# Generated by Django 4.2.23 on 2025-09-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0020_alter_perdidos_castrado_alter_perdidos_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdidos',
            name='pelagem',
            field=models.CharField(choices=[('nao-possui', 'Não Possui'), ('curta', 'Curta'), ('media', 'Média'), ('longa', 'Longa')], default='nao-possui', max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='pelagem',
            field=models.CharField(choices=[('nao-possui', 'Não Possui'), ('curta', 'Curta'), ('media', 'Média'), ('longa', 'Longa')], default='nao-possui', max_length=10),
        ),
        migrations.AlterField(
            model_name='perdidos',
            name='castrado',
            field=models.CharField(choices=[('sim', 'sim'), ('nao', 'nao')], default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='perdidos',
            name='genero',
            field=models.CharField(choices=[('macho', 'macho'), ('femea', 'femea')], default='macho', max_length=5),
        ),
        migrations.AlterField(
            model_name='perdidos',
            name='porte',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], default='pequeno', max_length=7),
        ),
        migrations.AlterField(
            model_name='perdidos',
            name='vacinado',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao'), ('parcialmente', 'Parcialmente'), ('nao-sei', 'Não sei')], default='nao', max_length=12),
        ),
        migrations.AlterField(
            model_name='pet',
            name='castrado',
            field=models.CharField(choices=[('sim', 'sim'), ('nao', 'nao')], default='nao', max_length=3),
        ),
        migrations.AlterField(
            model_name='pet',
            name='genero',
            field=models.CharField(choices=[('macho', 'macho'), ('femea', 'femea')], default='macho', max_length=5),
        ),
        migrations.AlterField(
            model_name='pet',
            name='porte',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], default='pequeno', max_length=7),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vacinado',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao'), ('parcialmente', 'Parcialmente'), ('nao-sei', 'Não sei')], default='nao', max_length=12),
        ),
    ]
