# Generated by Django 4.2.23 on 2025-09-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0021_perdidos_pelagem_pet_pelagem_alter_perdidos_castrado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perdidos',
            old_name='tipo',
            new_name='especie',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='tipo',
            new_name='especie',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='castrado',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='pelagem',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='porte',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='raca',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='vacinado',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pelagem',
        ),
        migrations.AddField(
            model_name='perdidos',
            name='caracteristicas',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Raca',
        ),
    ]
