# Generated by Django 4.2.23 on 2025-09-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0022_rename_tipo_perdidos_especie_rename_tipo_pet_especie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdidos',
            name='castrado',
            field=models.CharField(choices=[('sim', 'sim'), ('nao', 'nao')], default='nao', max_length=3),
        ),
        migrations.AddField(
            model_name='perdidos',
            name='pelagem',
            field=models.CharField(choices=[('nao-possui', 'Não Possui'), ('curta', 'Curta'), ('media', 'Média'), ('longa', 'Longa')], default='nao-possui', max_length=10),
        ),
        migrations.AddField(
            model_name='perdidos',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='perdidos',
            name='porte',
            field=models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], default='pequeno', max_length=7),
        ),
        migrations.AddField(
            model_name='perdidos',
            name='raca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perdidos',
            name='vacinado',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Nao'), ('parcialmente', 'Parcialmente'), ('nao-sei', 'Não sei')], default='nao', max_length=12),
        ),
    ]
