# Generated by Django 4.2.23 on 2025-09-17 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0023_perdidos_castrado_perdidos_pelagem_perdidos_peso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perdidos',
            name='castrado',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='pelagem',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='porte',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='raca',
        ),
        migrations.RemoveField(
            model_name='perdidos',
            name='vacinado',
        ),
    ]
