# Generated by Django 4.2.23 on 2025-09-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_image_user'),
        ('sistema', '0024_remove_perdidos_castrado_remove_perdidos_pelagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdidos',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
