# Generated by Django 4.2.23 on 2025-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0025_alter_perdidos_foto_alter_pet_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdidos',
            name='foto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
