# Generated by Django 4.2.23 on 2025-09-17 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_image_user'),
        ('sistema', '0025_alter_perdidos_foto_alter_pet_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdidos',
            name='foto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
