# Generated by Django 4.2.23 on 2025-09-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0026_alter_perdidos_foto_alter_pet_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='foto_perfil',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
