# Generated by Django 4.2.23 on 2025-09-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0027_alter_organizacao_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacao',
            name='foto_perfil',
        ),
        migrations.AddField(
            model_name='organizacao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='perdidos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
